# Generated by Django 2.0.7 on 2021-01-16 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='vechicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('vechicle_no', models.IntegerField(default=6)),
                ('start_meter_reading', models.FloatField()),
                ('desile_filling', models.FloatField()),
                ('trips', models.IntegerField()),
                ('end_meter_reading', models.FloatField()),
                ('instructions', models.CharField(default='Available', max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='images/')),
                ('slug', models.SlugField(default='vno')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
